esphome:
  name: voice_assistant_1
  friendly_name: "Voice Assistant"
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - priority: -100
      then:
        - light.turn_on:
            id: light_id
            brightness: 100%
            effect: rainbow
        - delay: 3s
        - light.turn_off: light_id

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
   
psram:
  mode: quad  # quad for N8R2 and octal for N16R8
  speed: 80MHz

# Enable logging
logger:
  hardware_uart: UART0
  level: INFO

# Enable Home Assistant API
api:
  on_client_connected:
    then:
      - delay: 50ms
      - light.turn_off: light_id
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
  on_client_disconnected:
    then:
      - voice_assistant.stop: 

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  ap:
    ssid: "Voice Assistant 1 AP"
    password: "12345678"

captive_portal:
web_server:
improv_serial:

# ========== SENSORS ==========

sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"

# ========== SWITCH (MUTE) ==========
switch:
  - platform: template
    id: mute
    name: Mute
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on: 
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - light.turn_on:
          id: light_id           
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
          effect: fast pulse 
      - delay: 2s
      - light.turn_on:
          id: light_id           
          red: 100%
          green: 0%
          blue: 0%
          brightness: 40%
          effect: none
    on_turn_off:
      - light.turn_on:
          id: light_id           
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: fast pulse 
      - delay: 2s
      - light.turn_off: light_id
      - micro_wake_word.start:
   
# ========== LIGHT ==========
light:
  - platform: esp32_rmt_led_strip
    id: light_id
    rgb_order: GRB
    pin: GPIO5
    num_leds: 3
    chipset: WS2812
    name: "Light"
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - addressable_rainbow:
          width: 10
          speed: 15
          
          
# ========== AUDIO HARDWARE ==========       
i2s_audio:
  - id: i2s_audio_mic_id
    i2s_lrclk_pin: GPIO3  #WS 
    i2s_bclk_pin: GPIO2   #SCK
  - id: i2s_audio_speaker_id
    i2s_lrclk_pin: GPIO6  #LRC 
    i2s_bclk_pin: GPIO7   #BLCK

microphone:
  - platform: i2s_audio
    id: microphone_id
    adc_type: external
    i2s_din_pin: GPIO4    #SD pin on the INMP441
    i2s_audio_id: i2s_audio_mic_id
    channel: left
    
speaker:
  # Hardware Speaker (Physical)
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO8   #DIN Pin of the MAX98357A
    i2s_audio_id: i2s_audio_speaker_id
    sample_rate: 48000
    channel: mono

# ========== WAKE WORD ==========
micro_wake_word:
  on_wake_word_detected:
    then:
      # Start Assistant
      - voice_assistant.start:
          wake_word: !lambda return wake_word;
      # LED Feedback
      - light.turn_on:
          id: light_id           
          brightness: 100%
          effect: rainbow
  models:
    - model: hey_jarvis

# ========== VOICE ASSISTANT ==========
voice_assistant:
  id: voice_assistant_id
  microphone: microphone_id
  noise_suppression_level: 1
  auto_gain: 31dBFS
  speaker: speaker_id
  
  on_listening:
    then:
      - light.turn_on:
          id: light_id
          red: 0%
          blue: 0%
          green: 100%
          brightness: 100%
          effect: none
          
  on_intent_start:
    then:
      - light.turn_on:
          id: light_id
          brightness: 100%
          effect: rainbow
          
  on_intent_end:
    then:
      - light.turn_off: light_id
      
  on_error:
    then:
      - light.turn_on:
          id: light_id
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
          effect: none
      - delay: 1s
      - light.turn_off: light_id
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
            
  on_end:
    then:
      - light.turn_off: light_id
      - wait_until:
          not:
            voice_assistant.is_running:
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
            
  on_idle:
    then:
      - light.turn_off: light_id